name: can-run-ci

env:
    NODE_OPTIONS: '--max_old_space_size=6144'

on:
    workflow_call: # This is important for reusable workflows

jobs:
    can-run-ci:
        runs-on: ubuntu-latest
        if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
        steps:
            - uses: 8BitJonny/gh-get-current-pr@1.4.0
              id: PR
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  sha: ${{ github.event.pull_request.head.sha }}
                  filterOutClosed: true

            - name: Check WIP in PR Title
              uses: embano1/wip@v1
              with:
                  title: '${{ steps.PR.outputs.pr_title }}'
                  regex: '^WIP'

            - uses: ArcBlock/action-lint-pull-request-title@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
