name: publish-to-npm

env:
    NODE_OPTIONS: '--max_old_space_size=6144'

on:
    push:
        branches:
            - master
            - main

jobs:
    can-run-ci:
        uses: ./.github/workflows/can-run-ci.yml

    integration:
        needs: can-run-ci
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
            - uses: pnpm/action-setup@v3
              with:
                  version: 10

            - name: Setup node
              uses: actions/setup-node@v4
              with:
                  node-version: 22.2.0
                  cache: npm

            - name: Cache node_modules
              id: cache-node-modules
              uses: actions/cache@v4
              with:
                  path: |
                      node_modules
                  key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node_modules-

            - name: Initialize
              run: npm install

            - name: Build
              run: |
                  npm run build

            - name: Publish npm
              run: |
                  npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_TOKEN }}"
                  VERSION=$(cat version | awk '{$1=$1;print}')
                  echo "publish version ${VERSION}"
                  npm publish --access=public
